version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      javascript:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /apps/desktop/src-tauri
    schedule:
      interval: weekly
    groups:
      rust:
        patterns:
          - "*"
